### ISSUE TITLE
Include better documentation about installation

### ISSUE THREAD

**Issue by mattdarveniza** [apexskier/nova-typescript#11]
Information about how to get this extension up and running seems to be somewhat lacking in the extension README.

It seems you're required to point the extension at the correct TS library file. First of all, that should probably be pointed out in the docs. Second, while there's a helpful label telling you what folder this would normally live in, it doesn't tell you _which_ file in that directory it should be pointing at.

I'm a daily user of typescript but don't know enough about it's internals to know what file to pick in that folder. I tried the obvious choices of `lib/typescript.js` `lib/tsserver.js` and `lib/tsserverlibrary.js` but none of those seemed to work?

I understand this looks more like a support request than an actual ticket (and it kind of is), but my main point is that a bit more documentation on installation would prevent future requests like mine. If I figure out how to get TS running in this extension I'd be happy to PR some documentation :)

**Comment by apexskier** [comment]
Hi @mattdarveniza, thanks for the feedback. I'm working on improving the docs now.

I want to clarify this point, and understand what your initial understanding is.

> It seems you're required to point the extension at the correct TS library file.

You shouldn't actually be _required_ to do this. The extension will find a local installation of typescript if you've Nova's workspace root is where your `package.json`/`node_modules` are (unless you've got a very non-standard setup - see below). Otherwise, it will self-install and fallback to it's own version of typescript.

The "Typescript Library" extension setting should only be used if you've got a non-standard setup (e.g. a yarn workspace with multiple versions of typescript, multiple packages as sub-directories of your workspace).

The sidebar will indicate that the extension has started up successfully and which version of typescript is being used.

<img width="235" alt="Screen Shot 2020-06-20 at 11 17 09" src="https://user-images.githubusercontent.com/329222/85198264-9b3ee000-b2e7-11ea-96ca-cdbb44b3ed17.png">

**Comment by apexskier** [comment]
(also, after rediving into the code, the custom lib location is totally broken, so I'll be fixing it)

**Comment by apexskier** [comment]
@mattdarveniza Can you take a look at https://github.com/apexskier/nova-typescript/pull/12/files#diff-6a27db6fe77caf3880106256904b6063 and https://github.com/apexskier/nova-typescript/pull/12/files#diff-7bb9058af4eb1fab885414a8a1657071?

**Comment by mattdarveniza** [comment]
Looks great, much clearer! Thank you 😄

**Comment by Ggpsv** [comment]
Hi @apexskier! I haven't been able to get the extension working. I get the `TypeScript[12:58:01.795000] Error: failed to install
` error each time it attempts to activate. It happens regardless of specifying a path in the extension config. Is there something I'm missing?

**Comment by apexskier** [comment]
@Ggpsv Would you mind opening a new issue and filling out the bug report template? It'll help me a lot if I know more about your environment.

**Comment by Ggpsv** [comment]
Sure thing!

**Comment by zackrdavis** [comment]
In case this helps anybody else, the issue that brought me here was actually a system PATH issue. I found my solution here: https://dev.panic.com/panic/nova-issues/-/issues/1488
