### ISSUE TITLE
TypeScript definition not recognized in Svelte script tag

### ISSUE THREAD

**Issue by acarr** [apexskier/nova-typescript#234]
Working on a project where I have a local `*.d.ts` file with some defined types in it. Nova is able to find the declaration file and provide IntelliSense in all *.ts files in the project. 

But using TypeScript within a Svelte component script tag does not recognize the types from the declaration file. This _may_ be a TypeScript extension issue but it could be an issue with the Svelte extension—I'm not sure but checking here.

So given a declaration file like in `global.d.ts`...
```typescript
// global.d.ts
interface User {
  firstName: string;
  lastName: string;
  age?: number;
}
```

the types are recognized correctly in the `main.ts` file in the Svelte project.
```typescript
// main.ts
import App from './App.svelte';
let test:User = {
	firstName: "Aria",
	lastName: "Stark"
}
const app = new App({
	target: document.body,
	props: {
		user: test
	}
});
export default app;
```

And a screenshot of the same in Nova:
<img width="438" alt="CleanShot 2021-04-06 at 21 47 08@2x" src="https://user-images.githubusercontent.com/237203/113798690-abfafe00-9721-11eb-8748-b82811d96161.png">

But inside of a Svelte component, Nova does not recognize the `User` type.
```svelte
<!-- App.svelte -->
<script lang="ts">
	export let user: User;
</script>

<main>
	<h1>Hello {user.firstName} {user.lastName} {user.age}!</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
</main>

```

And a screenshot of the error in Nova:
<img width="408" alt="CleanShot 2021-04-06 at 21 48 30@2x" src="https://user-images.githubusercontent.com/237203/113798801-df3d8d00-9721-11eb-9b4c-d621ddf65172.png">

Any thoughts or direction on where the issue might lie is appreciated.

**To reproduce**

1. Open the example project here: https://github.com/acarr/svelte-ts-nova-test
2. Install the [Svelte](nova://extension/?id=sb.lao.svelte-nova&name=Svelte) extension for Svelte syntax highlighting
3. View errors in the `App.svelte` file

**Expected behavior**

Expect the Typescript types to be recognized within the Svelte file script tag.

**Environment**

- Nova version: 5.1 Build 257074
- Extension version: 2.1.1
- TypeScript version: 4.2.3
- Sidebar information: 4.2.3
- macOS version: 11.2.2
- NodeJS information:
  - node version: 12.13.1
  - npm version: 6.12.1

**Comment by apexskier** [comment]
I've got your example project downloaded (very helpful!), 2.4.0 (just released) of this typescript extension, 0.1.6 of the svelte extension (sb.lao.svelte-nova).

I'm not experiencing the same issues you are, but I do think there are some issues with the Svelte language server used by the svelte plugin.

I'm not seeing errors shown for the `User` type in the `.svelte` file. I also see jump to definition working for it, but it's _very_ slow the first time (>10 seconds), and I suspect based on some messages I saw in the logs that the svelte server might need the `global.d.ts` file where it's defined to have been previously opened for it to know about it.

https://user-images.githubusercontent.com/329222/124389337-e8210900-dce6-11eb-834a-737f23e224fd.mp4

Given that this extension [explicitly doesn't process `.svelte` files](https://github.com/apexskier/nova-typescript/blob/a8aaa3b83e366593a80517c3cbe646da31f08821/src/main.ts#L150-L153) but the svelte extension is providing some typescript support in svelte files, I think the cause is somewhere in its language server.
