### ISSUE TITLE
Returning after “Jump to Definition”

### ISSUE THREAD

**Issue by smockle** [apexskier/nova-typescript#235]
When I right-click the `toLowerCase` call in `index.ts` below and select “Jump to Definition”, `utils.ts` is opened and scrolled so the function definition is viewable.

Is there a command to return to the original position (`index.ts` with the function call in-view)? I expected the “Go → Back” item in Nova’s menu bar to accomplish this, but it’s disabled (grayed out).

```ts
// index.ts
import { toLowerCase } from "./utils"
const output = toLowerCase("ASDF")
console.log(output)
```

```ts
// utils.ts
function toLowerCase(x: string): string {
  return x.toLowerCase()
}
```

<img width="653" alt="nova-go-back" src="https://user-images.githubusercontent.com/3104489/114436958-f4884080-9b93-11eb-9ac1-73aefcd38a8b.png">

**Comment by apexskier** [comment]
The "Jump to Definition" functionality is no longer managed by this extension as of [v2](https://github.com/apexskier/nova-typescript/blob/main/typescript.novaextension/CHANGELOG.md#v200), since Nova provides it directly through the language service. I can't do anything from this extension to support this, but it definitely seems like it should work. Can you please report this [directly to Panic](https://nova.app/help/?ext=TypeScript%20(apexskier.typescript)%20(reported%20from%20https%3A%2F%2Fgithub.com%2Fapexskier%2Fnova-typescript%2Fissues%2Fnew))?

**Comment by smockle** [comment]
From @apexskier in https://github.com/apexskier/nova-typescript/issues/235#issuecomment-826065869

> The "Jump to Definition" functionality is no longer managed by this extension as of [v2](https://github.com/apexskier/nova-typescript/blob/main/typescript.novaextension/CHANGELOG.md#v200), since Nova provides it directly through the language service. I can't do anything from this extension to support this, but it definitely seems like it should work. Can you please report this [directly to Panic](https://nova.app/help/?ext=TypeScript%20(apexskier.typescript)%20(reported%20from%20https%3A%2F%2Fgithub.com%2Fapexskier%2Fnova-typescript%2Fissues%2Fnew))?

Thanks for the clarification! I’ll report the issue to Panic 👍 Closing since this issue is unfixable.
