### ISSUE TITLE
Allow Ability to Set Preference on Unused Import Removal

### ISSUE THREAD

**Issue by rehatkathuria** [apexskier/nova-typescript#273]
First of all: Thank you for your work on this! I have a habit of hitting CMD + S often as I'm writing code. Having the formatter organise and rearrange imports during those keystrokes is great –– however, having it remove an import that I haven't yet used is a little frustrating. I'd really appreciate the ability to disable that functionality.

**Comment by apexskier** [comment]
Looks like this might be possible. `tsserver` has a `skipDestructiveCodeActions` argument that skips the remove unused arguments logic.

https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/services/organizeImports.ts#L91-L95

In order to implement this I'll need to pass that through from `typescript-language-server` as an argument [here](https://github.com/theia-ide/typescript-language-server/blob/f43aff23b9eaaae83d11a422fb509667951b2104/server/src/lsp-server.ts#L749), which will require work in that codebase.

Then I can pass an option from the extension here:

https://github.com/apexskier/nova-typescript/blob/0d04b61e79f2e90bcc68190ee96a338bb1bb5aa5/src/commands/organizeImports.ts#L54

**Comment by apexskier** [comment]
It looks like this feature will be new in TypeScript 4.4, which is still in beta currently:

https://github.com/microsoft/TypeScript/pull/43184

**Comment by apexskier** [comment]
Another option I'd recommend if you're looking to improve your experience is to disable organize imports on save through this extension and replace it with an ESLint rule that organizes imports, using https://github.com/apexskier/nova-eslint, and enabling eslint's fix on save.
