### ISSUE TITLE
Able to summon suggestions at any time?

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-typescript#30]
In VSCode, it's possible to summon a list of the best suggestions TS can come up with by pressing Ctrl + Space.

This is useful in situations when you'd like to see the available exports on a package, or any situation where you don't know the first few characters of a token.

Is this possible in this extension, or in Nova?

**Comment by apexskier** [comment]
Ideally Nova would allow you to summon its completions at any time, instead of just when you are typing - I think that's a valid feature request for the Nova team and should be the ultimate resolution.

---

This made me curious about language server provided completions in general, so I tried adding a manual request to `textDocument/completion`. I expected Nova to intercept the response, since that's what it does for `textDocument/publishDiagnostics` which I think it uses internally. It doesn't intercept it though, so Nova might not be using the language server for completion. I know Nova doesn't use a [bunch of the features](https://github.com/apexskier/nova-typescript/search?q=%22decoupled+from+typescript%22&unscoped_q=%22decoupled+from+typescript%22) from the Language Server Protocol, so I've implemented them manually in this plugin.

I started experimenting to see if the suggestions provided by the language server are better, and to see if I can register my own Nova completion assistant. I'd like to use a completion assistant, but I haven't gotten it working yet. With what's currently available from Nova's extension API I can't create a _great_ UI for presenting suggestions outside of this (closest is choice picker, which only allows a single bit of text). You can play with it in my branch at https://github.com/apexskier/nova-typescript/pull/31.

<img width="681" alt="Screen Shot 2020-08-10 at 21 23 53" src="https://user-images.githubusercontent.com/329222/89823047-163aaf00-db51-11ea-9609-4c15d37779ea.png">

**Comment by sgwilym** [comment]
Thanks for exploring this! I've filed a feature request at https://dev.panic.com/panic/nova-issues/-/issues/1464

**Comment by apexskier** [comment]
I've done some more playing around and have discovered some things

1. Registering a [completion assistant](https://novadocs.panic.com/api-reference/assistants-registry/#registercompletionassistant-selector-object) has no effect if a language server is running. ([here's a test branch](https://github.com/apexskier/nova-typescript/blob/f3b6f76a64ab634e552af0a631e5f08a387fc2de/src/main.ts#L104-L112)). 
2. The completion assistant interface is purely synchronous - this means I can't provide a custom one with a language server.

In 1.6.0 / #31 I'm adding an experimental feature that adds basic support for manual suggestion summoning through a best-effort UI. You can bind the command to a keyboard shortcut through nova's keybinding settings. Once it's out, let me know how it goes.

**Comment by sgwilym** [comment]
@apexskier I checked out the new feature this morning - it's actually pretty usable if it weren't for that last insert dialogue!

https://dev.panic.com/panic/nova-issues/-/issues/1518#note_7537
> If there's anything we can do from Nova's side to make this simpler for them, we are happy to investigate!

Hope springs eternal.

**Comment by apexskier** [comment]
Can you clarify what insert dialog you're referring to? It might be one I've added myself.

**Comment by sgwilym** [comment]
@apexskier This one:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/579491/91171462-cc1e0580-e6da-11ea-8e3b-80ead323b845.png">

**Comment by apexskier** [comment]
I can get rid of that. I added it because the prior choice picker has pretty much nothing I can do to add more context that is provided by the language server.

Instead, I think it makes more sense to introduce a "show documentation" type of command that lets you see more information about a symbol (a lot provide documentation through doc comments). I was playing around with that in https://github.com/apexskier/nova-typescript/compare/signature-help.

**Comment by apexskier** [comment]
Somewhat related to this is a Nova bug I discovered that should be fixed in v1.3. Language server trigger character, such as "." aren't triggering auto complete like they should.

Some info from an email thread with Nova support:

**Comment by apexskier** [comment]
> * Registering a [completion assistant](https://novadocs.panic.com/api-reference/assistants-registry/#registercompletionassistant-selector-object) has no effect if a language server is running. ([here's a test branch](https://github.com/apexskier/nova-typescript/blob/f3b6f76a64ab634e552af0a631e5f08a387fc2de/src/main.ts#L104-L112)).

Additiona

> * The completion assistant interface is purely synchronous - this means I can't provide a custom one with a language server.

**Comment by apexskier** [comment]
Additionally, these are resolved

> * Registering a [completion assistant](https://novadocs.panic.com/api-reference/assistants-registry/#registercompletionassistant-selector-object) has no effect if a language server is running. ([here's a test branch](https://github.com/apexskier/nova-typescript/blob/f3b6f76a64ab634e552af0a631e5f08a387fc2de/src/main.ts#L104-L112)).

Nova 1.2 allows registering a completion assistant with an LSP client running

> * The completion assistant interface is purely synchronous - this means I can't provide a custom one with a language server.

In the same support thread they told me this does return a promise, and the [docs have been updated to reflect that](https://docs.nova.app/api-reference/assistants-registry/#registercompletionassistant-selector-object).

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48340 ⬅️ An approval on this would be helpful!

**Comment by apexskier** [comment]
Nova 2 has support for this natively - Editor > Show Completions, which is bound to <kbd>^</kbd> <kbd>Space</kbd> by default.
